/**
 * Seed data: real Apple products with official specifications
 * Categories + Products for Prisma seed
 */
// صور من Unsplash — تعمل من أي دومين (لا حظر hotlink)
const U = (id: string, w = 800, h = 800) => `https://images.unsplash.com/photo-${id}?w=${w}&h=${h}&fit=crop`;
export const seedCategories = [
  { slug: "iphone", name: "iPhone", description: "Powerful. Beautiful.", image: U("1592750475338-74b7b21085ab", 600, 600) },
  { slug: "ipad", name: "iPad", description: "Magic happens here.", image: U("1544244015-0df4b3ffc6b0", 600, 600) },
  { slug: "macbook-m1", name: "MacBook M1", description: "Apple Silicon M1 — Air 13\", Pro 13\" / 14\" / 16\".", image: U("1517336714731-489689fd1ca8", 600, 600) },
  { slug: "macbook-m2", name: "MacBook M2", description: "Apple Silicon M2 — Air 13\" / 15\", Pro 14\" / 16\".", image: U("1517336714731-489689fd1ca8", 600, 600) },
  { slug: "macbook-m3", name: "MacBook M3", description: "Apple Silicon M3 — Air 13\" / 15\", Pro 14\" / 16\".", image: U("1517336714731-489689fd1ca8", 600, 600) },
  { slug: "macbook-m4", name: "MacBook M4", description: "Apple Silicon M4 — Air 13\", Pro 14\" / 16\".", image: U("1517336714731-489689fd1ca8", 600, 600) },
  { slug: "macbook-m5", name: "MacBook M5", description: "Apple Silicon M5 — أحدث جيل.", image: U("1517336714731-489689fd1ca8", 600, 600) },
  { slug: "imac", name: "iMac", description: "All-in-one. 24\" 4.5K. M1 / M3. موديلات حسب السنة.", image: U("1527443224154-c4a3942d3acf", 600, 600) },
  { slug: "mac-mini", name: "Mac mini", description: "Desktop compact. M1 / M2 / M4. موديلات حسب السنة.", image: U("1527443224154-c4a3942d3acf", 600, 600) },
  { slug: "mac-studio", name: "Mac Studio", description: "Pro desktop. M1 Max/Ultra, M2 Max/Ultra. موديلات حسب السنة.", image: U("1527443224154-c4a3942d3acf", 600, 600) },
  { slug: "mac-pro", name: "Mac Pro", description: "Workstation. M2 Ultra. توسعات PCIe. موديل حسب السنة.", image: U("1527443224154-c4a3942d3acf", 600, 600) },
  { slug: "watch", name: "Apple Watch", description: "The ultimate device for a healthy life.", image: U("1434493789847-2f02dc6ca35d", 600, 600) },
  { slug: "airpods", name: "AirPods", description: "Sound that surrounds you.", image: U("1587523459887-e669248cf666", 600, 600) },
  { slug: "appletv", name: "Apple TV", description: "Cinema in your living room.", image: U("1593359677879-a4bb92f829d1", 600, 600) },
  { slug: "accessories", name: "Accessories", description: "Chargers, USB cables, cases, MagSafe & more.", image: U("1583394838336-acd977736f90", 600, 600) },
  { slug: "repair", name: "Repair", description: "Laptops, mobiles & software.", image: U("1721333084062-71c1f242459a", 600, 600) },
];

export const seedProducts = [
  // ——— iPhone ———
  {
    slug: "iphone-16-pro-max",
    name: "iPhone 16 Pro Max",
    categorySlug: "iphone",
    description: "The most advanced iPhone. 6.9-inch Super Retina XDR display, A18 Pro chip, pro camera system with 48MP Main and 5x optical zoom. Titanium design, Ceramic Shield, IP68. Apple Intelligence built in.",
    shortDescription: "6.9\" Super Retina XDR. A18 Pro. 48MP Pro camera. Titanium.",
    price: 1199,
    currency: "USD",
    badge: "New",
    inStock: true,
    rating: 4.9,
    reviewCount: 3240,
    images: [U("1592750475338-74b7b21085ab")],
    specs: [
      { label: "Display", value: "6.9\" Super Retina XDR OLED, 2868×1320, 460 ppi, ProMotion 120Hz, 2000 nits peak" },
      { label: "Chip", value: "A18 Pro — 6-core CPU, 6-core GPU, 16-core Neural Engine" },
      { label: "Camera", value: "48MP Main (ƒ/1.78), 48MP Ultra Wide (ƒ/2.2), 12MP 5x Telephoto (ƒ/2.8); 4K Dolby Vision 120fps" },
      { label: "Storage", value: "256GB / 512GB / 1TB" },
      { label: "Battery", value: "Video playback up to 29 hours" },
      { label: "Durability", value: "IP68 (6m, 30 min); Ceramic Shield; Titanium" },
      { label: "Weight", value: "227 g" },
    ],
    colors: [
      { name: "Black Titanium", hex: "#1a1a1a" },
      { name: "White Titanium", hex: "#f5f5f0" },
      { name: "Natural Titanium", hex: "#c4b8a8" },
      { name: "Desert Titanium", hex: "#b8956b" },
    ],
  },
  {
    slug: "iphone-16-pro",
    name: "iPhone 16 Pro",
    categorySlug: "iphone",
    description: "Pro camera. A18 Pro. 6.3-inch Super Retina XDR. Titanium. Apple Intelligence.",
    shortDescription: "6.3\" Super Retina XDR. A18 Pro. 48MP. Titanium.",
    price: 999,
    currency: "USD",
    badge: "New",
    inStock: true,
    rating: 4.8,
    reviewCount: 2891,
    images: [U("1510557880182-3d4d3cba35a5")],
    specs: [
      { label: "Display", value: "6.3\" Super Retina XDR OLED, ProMotion 120Hz, 2000 nits peak" },
      { label: "Chip", value: "A18 Pro — 6-core CPU, 6-core GPU, 16-core Neural Engine" },
      { label: "Camera", value: "48MP Main, 48MP Ultra Wide, 12MP 5x Telephoto; 4K Dolby Vision" },
      { label: "Storage", value: "128GB / 256GB / 512GB / 1TB" },
      { label: "Durability", value: "IP68; Ceramic Shield; Titanium" },
    ],
    colors: [
      { name: "Black Titanium", hex: "#1a1a1a" },
      { name: "White Titanium", hex: "#f5f5f0" },
      { name: "Natural Titanium", hex: "#c4b8a8" },
      { name: "Desert Titanium", hex: "#b8956b" },
    ],
  },
  {
    slug: "iphone-16",
    name: "iPhone 16",
    categorySlug: "iphone",
    description: "A18 chip. 6.3-inch Super Retina XDR. 48MP Main camera. Advanced dual-camera system. Aluminum design.",
    shortDescription: "6.3\" Super Retina XDR. A18. 48MP. Five colors.",
    price: 799,
    currency: "USD",
    badge: "New",
    inStock: true,
    rating: 4.7,
    reviewCount: 4102,
    images: [U("1592286927505-d6d2a7a029c7")],
    specs: [
      { label: "Display", value: "6.3\" Super Retina XDR, 60Hz, 2000 nits peak (HDR)" },
      { label: "Chip", value: "A18 — 6-core CPU, 6-core GPU, 16-core Neural Engine" },
      { label: "Camera", value: "48MP Main (ƒ/1.6), 12MP Ultra Wide (ƒ/2.4); 4K video" },
      { label: "Storage", value: "128GB / 256GB / 512GB" },
      { label: "Durability", value: "IP68; Ceramic Shield" },
    ],
    colors: [
      { name: "Black", hex: "#1d1d1f" },
      { name: "White", hex: "#fbfbfd" },
      { name: "Blue", hex: "#4a90d9" },
      { name: "Green", hex: "#34c759" },
      { name: "Pink", hex: "#ff9ff3" },
    ],
  },
  {
    slug: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    categorySlug: "iphone",
    description: "A17 Pro chip. 6.7-inch Super Retina XDR. 48MP Main, 5x optical zoom. Titanium. Action button.",
    shortDescription: "A17 Pro. 48MP. 5x zoom. Titanium.",
    price: 1099,
    currency: "USD",
    badge: "Pro",
    inStock: true,
    rating: 4.8,
    reviewCount: 2847,
    images: [U("1592750475338-74b7b21085ab")],
    specs: [
      { label: "Display", value: "6.7\" Super Retina XDR OLED, ProMotion 120Hz, 2000 nits peak" },
      { label: "Chip", value: "A17 Pro — 6-core CPU, 6-core GPU, 16-core Neural Engine" },
      { label: "Camera", value: "48MP Main, 12MP Ultra Wide, 12MP 5x Telephoto; ProRAW; 4K ProRes" },
      { label: "Storage", value: "256GB / 512GB / 1TB" },
      { label: "Durability", value: "IP68; Titanium" },
    ],
    colors: [
      { name: "Black Titanium", hex: "#1a1a1a" },
      { name: "White Titanium", hex: "#f5f5f0" },
      { name: "Natural Titanium", hex: "#c4b8a8" },
      { name: "Blue Titanium", hex: "#5e7fa5" },
    ],
  },
  {
    slug: "iphone-15",
    name: "iPhone 15",
    categorySlug: "iphone",
    description: "A16 Bionic. 6.1-inch Super Retina XDR. 48MP Main. Dynamic Island. USB-C.",
    shortDescription: "A16. 48MP. Dynamic Island. Five colors.",
    price: 699,
    currency: "USD",
    badge: "Best Seller",
    inStock: true,
    rating: 4.6,
    reviewCount: 5200,
    images: [U("1592286927505-d6d2a7a029c7")],
    specs: [
      { label: "Display", value: "6.1\" Super Retina XDR, 60Hz, 2000 nits peak" },
      { label: "Chip", value: "A16 Bionic — 6-core CPU, 5-core GPU" },
      { label: "Camera", value: "48MP Main, 12MP Ultra Wide; 4K video" },
      { label: "Storage", value: "128GB / 256GB / 512GB" },
      { label: "Durability", value: "IP68" },
    ],
    colors: [
      { name: "Black", hex: "#1d1d1f" },
      { name: "Blue", hex: "#4a90d9" },
      { name: "Green", hex: "#34c759" },
      { name: "Pink", hex: "#ff9ff3" },
      { name: "Yellow", hex: "#ffd60a" },
    ],
  },
  // ——— MacBook (فئات: M1–M5، نوع: Air / Pro، حجم شاشة: 13\" / 14\" / 15\" / 16\"، موديل السنة) ———
  {
    slug: "macbook-pro-14-m4",
    name: "MacBook Pro 14\" (M4, 2024)",
    categorySlug: "macbook-m4",
    subcategory: "Pro 14\"",
    description: "14.2-inch Liquid Retina XDR. M4 chip — 10-core CPU, 10-core GPU. Up to 24 hours battery. 16GB/512GB base. Space Black or Silver.",
    shortDescription: "M4. 14.2\" Liquid Retina XDR. 24h battery.",
    price: 1599,
    currency: "USD",
    badge: "New",
    inStock: true,
    rating: 4.9,
    reviewCount: 892,
    images: [U("1517336714731-489689fd1ca8")],
    specs: [
      { label: "Model Year", value: "2024" },
      { label: "Chip", value: "M4 — 10-core CPU, 10-core GPU, 16-core Neural Engine; 120GB/s memory bandwidth" },
      { label: "Display", value: "14.2\" Liquid Retina XDR — 3024×1964, 254 ppi, ProMotion 120Hz, 1000 nits sustained, 1600 nits HDR" },
      { label: "Memory", value: "16GB or 24GB unified memory (up to 32GB)" },
      { label: "Storage", value: "512GB or 1TB SSD (up to 2TB)" },
      { label: "Battery", value: "Up to 24 hours video playback; 72.4Wh; 70W adapter" },
      { label: "Ports", value: "3× Thunderbolt 4, HDMI, SDXC, MagSafe 3, 3.5mm" },
      { label: "Connectivity", value: "Wi‑Fi 6E; Bluetooth 5.3" },
    ],
    colors: [
      { name: "Space Black", hex: "#1a1a1a" },
      { name: "Silver", hex: "#e8e8e8" },
    ],
  },
  {
    slug: "macbook-pro-16-m4-pro",
    name: "MacBook Pro 16\" (M4 Pro, 2024)",
    categorySlug: "macbook-m4",
    subcategory: "Pro 16\"",
    description: "16.2-inch Liquid Retina XDR. M4 Pro or M4 Max. Up to 22 hours battery. Pro performance for creators and developers.",
    shortDescription: "M4 Pro/Max. 16.2\" XDR. 22h battery.",
    price: 2499,
    currency: "USD",
    badge: "Pro",
    inStock: true,
    rating: 4.9,
    reviewCount: 645,
    images: [U("1611186871348-b1ce696e52c9")],
    specs: [
      { label: "Model Year", value: "2024" },
      { label: "Chip", value: "M4 Pro — 14-core CPU, 18-core GPU; or M4 Max — 16-core CPU, 40-core GPU" },
      { label: "Display", value: "16.2\" Liquid Retina XDR — 3456×2234, 254 ppi, ProMotion 120Hz, 1000 nits sustained" },
      { label: "Memory", value: "18GB–128GB unified memory" },
      { label: "Storage", value: "512GB–2TB SSD" },
      { label: "Battery", value: "Up to 22 hours video; 100Wh; 140W adapter" },
      { label: "Ports", value: "3× Thunderbolt 4, HDMI, SDXC, MagSafe 3, 3.5mm" },
    ],
    colors: [
      { name: "Space Black", hex: "#1a1a1a" },
      { name: "Silver", hex: "#e8e8e8" },
    ],
  },
  {
    slug: "macbook-air-m3-13",
    name: "MacBook Air 13\" (M3, 2024)",
    categorySlug: "macbook-m3",
    subcategory: "Air 13\"",
    description: "13.6-inch Liquid Retina. M3 chip. Up to 18 hours battery. 0.44 inch thin. Midnight, Starlight, Space Gray, Silver.",
    shortDescription: "M3. 13.6\" Liquid Retina. 18h. 0.44\" thin.",
    price: 1099,
    currency: "USD",
    badge: "Best Seller",
    inStock: true,
    rating: 4.8,
    reviewCount: 2103,
    images: [U("1611186871348-b1ce696e52c9")],
    specs: [
      { label: "Model Year", value: "2024" },
      { label: "Chip", value: "M3 — 8-core CPU, 10-core GPU, 16-core Neural Engine" },
      { label: "Display", value: "13.6\" Liquid Retina — 2560×1664, 224 ppi, 500 nits" },
      { label: "Memory", value: "8GB or 16GB unified memory" },
      { label: "Storage", value: "256GB, 512GB, or 1TB SSD" },
      { label: "Battery", value: "Up to 18 hours; 52.6Wh" },
      { label: "Weight", value: "1.24 kg (2.7 lb)" },
    ],
    colors: [
      { name: "Midnight", hex: "#1e1e2e" },
      { name: "Starlight", hex: "#f5e6d3" },
      { name: "Space Gray", hex: "#53525c" },
      { name: "Silver", hex: "#e8e8e8" },
    ],
  },
  // ——— iPad ———
  {
    slug: "ipad-pro-13-m4",
    name: "iPad Pro 13\" (M4, 2024)",
    categorySlug: "ipad",
    description: "Ultra-thin design. M4 chip. 13-inch Tandem OLED — stunning brightness and contrast. Pro cameras. Apple Pencil Pro.",
    shortDescription: "M4. 13\" Tandem OLED. Ultra-thin.",
    price: 1299,
    currency: "USD",
    badge: "New",
    inStock: true,
    rating: 4.9,
    reviewCount: 456,
    images: [U("1544244015-0df4b3ffc6b0")],
    specs: [
      { label: "Chip", value: "M4 — 10-core CPU, 10-core GPU, 16-core Neural Engine" },
      { label: "Display", value: "13\" Tandem OLED — 2752×2064, 264 ppi, ProMotion 120Hz, 1000 nits SDR, 1600 nits HDR" },
      { label: "Storage", value: "256GB / 512GB / 1TB / 2TB" },
      { label: "Camera", value: "12MP Ultra Wide front (Center Stage); 12MP rear" },
      { label: "Thickness", value: "5.1 mm" },
    ],
    colors: [
      { name: "Space Black", hex: "#1a1a1a" },
      { name: "Silver", hex: "#e8e8e8" },
    ],
  },
  {
    slug: "ipad-air-m2-11",
    name: "iPad Air 11\" (M2)",
    categorySlug: "ipad",
    description: "11-inch Liquid Retina. M2 chip. All-day battery. Supports Apple Pencil Pro and Magic Keyboard.",
    shortDescription: "M2. 11\" Liquid Retina. Pencil Pro.",
    price: 599,
    currency: "USD",
    badge: "Best Seller",
    inStock: true,
    rating: 4.7,
    reviewCount: 1892,
    images: [U("1544244015-0df4b3ffc6b0")],
    specs: [
      { label: "Chip", value: "M2 — 8-core CPU, 10-core GPU" },
      { label: "Display", value: "11\" Liquid Retina — 2360×1640, 264 ppi, 500 nits" },
      { label: "Storage", value: "128GB / 256GB / 512GB / 1TB" },
      { label: "Battery", value: "All-day battery" },
    ],
    colors: [
      { name: "Blue", hex: "#4a90d9" },
      { name: "Purple", hex: "#bf5af2" },
      { name: "Starlight", hex: "#f5e6d3" },
      { name: "Space Gray", hex: "#53525c" },
    ],
  },
  // ——— iMac (أجهزة سطح المكتب — موديل السنة) ———
  {
    slug: "imac-24-m3",
    name: "iMac 24\" (M3, 2024)",
    categorySlug: "imac",
    subcategory: "24\" M3",
    description: "24-inch 4.5K Retina display. M3 chip. Seven vibrant colors. All-in-one design with 1080p FaceTime camera and six-speaker sound system.",
    shortDescription: "24\" 4.5K Retina. M3. Seven colors.",
    price: 1299,
    currency: "USD",
    badge: "New",
    inStock: true,
    rating: 4.8,
    reviewCount: 734,
    images: [U("1527443224154-c4a3942d3acf")],
    specs: [
      { label: "Model Year", value: "2024" },
      { label: "Chip", value: "M3 — 8-core CPU, 10-core GPU" },
      { label: "Display", value: "24\" 4.5K Retina — 4480×2520, 218 ppi, 500 nits, P3" },
      { label: "Memory", value: "8GB unified memory (16GB or 24GB configurable)" },
      { label: "Storage", value: "256GB / 512GB / 1TB / 2TB SSD" },
      { label: "Camera", value: "1080p FaceTime HD camera" },
      { label: "Audio", value: "Six-speaker system with Spatial Audio" },
    ],
    colors: [
      { name: "Blue", hex: "#4a90d9" },
      { name: "Green", hex: "#34c759" },
      { name: "Pink", hex: "#ff9ff3" },
      { name: "Yellow", hex: "#ffd60a" },
      { name: "Orange", hex: "#ff9f0a" },
      { name: "Purple", hex: "#bf5af2" },
      { name: "Silver", hex: "#e8e8e8" },
    ],
  },
  // ——— Apple Watch ———
  {
    slug: "apple-watch-ultra-2",
    name: "Apple Watch Ultra 2",
    categorySlug: "watch",
    description: "49mm titanium case. Brightest display (3000 nits). S9 SiP. Precision Dual-Frequency GPS. 36-hour battery. Action button. Ocean, Alpine, Trail bands.",
    shortDescription: "49mm Titanium. 3000 nits. 36h battery.",
    price: 799,
    currency: "USD",
    badge: "Pro",
    inStock: true,
    rating: 4.8,
    reviewCount: 1203,
    images: [U("1434493789847-2f02dc6ca35d")],
    specs: [
      { label: "Case", value: "49mm titanium; 100m water resistant; EN13319 dive" },
      { label: "Display", value: "Always-On Retina LTPO OLED, 3000 nits peak" },
      { label: "Chip", value: "S9 SiP — 64-bit dual-core; 4-core GPU" },
      { label: "Battery", value: "Up to 36 hours; 72-hour Low Power Mode" },
      { label: "GPS", value: "Precision Dual-Frequency GPS (L1 + L5)" },
    ],
    colors: [
      { name: "Titanium (Natural)", hex: "#c4b8a8" },
      { name: "Titanium (Dark)", hex: "#2c2c2e" },
    ],
  },
  {
    slug: "apple-watch-series-10",
    name: "Apple Watch Series 10",
    categorySlug: "watch",
    description: "Thinner design. Larger display. S10 SiP. Double Tap. 18-hour battery. Aluminum or stainless steel.",
    shortDescription: "Thinner. Larger display. S10. Double Tap.",
    price: 399,
    currency: "USD",
    badge: "New",
    inStock: true,
    rating: 4.7,
    reviewCount: 892,
    images: [U("1434493789847-2f02dc6ca35d")],
    specs: [
      { label: "Case", value: "42mm or 46mm; 50m water resistant" },
      { label: "Display", value: "Always-On Retina; 2000 nits peak" },
      { label: "Chip", value: "S10 SiP" },
      { label: "Battery", value: "Up to 18 hours" },
      { label: "Features", value: "Double Tap; Crash Detection; Temperature sensing" },
    ],
    colors: [
      { name: "Aluminum (Silver)", hex: "#e8e8e8" },
      { name: "Aluminum (Midnight)", hex: "#1e1e2e" },
      { name: "Aluminum (Starlight)", hex: "#f5e6d3" },
      { name: "Aluminum (Pink)", hex: "#ff9ff3" },
      { name: "Stainless Steel (Gold)", hex: "#d4af37" },
      { name: "Stainless Steel (Graphite)", hex: "#3d3d3d" },
    ],
  },
  // ——— AirPods ———
  {
    slug: "airpods-pro-2",
    name: "AirPods Pro (2nd generation)",
    categorySlug: "airpods",
    description: "Active Noise Cancellation. Adaptive Audio. Personalized Spatial Audio. H2 chip. Up to 6 hours ANC. MagSafe Charging Case with Find My and speaker.",
    shortDescription: "ANC. Adaptive Audio. H2. 6h ANC.",
    price: 249,
    currency: "USD",
    badge: "Best Seller",
    inStock: true,
    rating: 4.8,
    reviewCount: 4521,
    images: [U("1587523459887-e669248cf666")],
    specs: [
      { label: "Chip", value: "H2" },
      { label: "Audio", value: "Active Noise Cancellation; Adaptive Audio; Transparency; Personalized Spatial Audio" },
      { label: "Battery", value: "Up to 6 hours with ANC; 30 hours total with case" },
      { label: "Case", value: "MagSafe; Find My; speaker; USB-C" },
    ],
    colors: [{ name: "White", hex: "#f5f5f5" }],
  },
  {
    slug: "airpods-max",
    name: "AirPods Max",
    categorySlug: "airpods",
    description: "Over-ear. Computational Audio. Active Noise Cancellation. Transparency. Spatial Audio. 20 hours battery. Aluminum cups. Five colors.",
    shortDescription: "Over-ear. Computational Audio. ANC. 20h.",
    price: 549,
    currency: "USD",
    badge: "Premium",
    inStock: true,
    rating: 4.6,
    reviewCount: 1823,
    images: [U("1587523459887-e669248cf666")],
    specs: [
      { label: "Driver", value: "40mm dynamic driver; dual neodymium ring magnet" },
      { label: "Audio", value: "Active Noise Cancellation; Transparency; Spatial Audio with head tracking" },
      { label: "Battery", value: "Up to 20 hours ANC" },
      { label: "Chip", value: "H1" },
    ],
    colors: [
      { name: "Space Gray", hex: "#53525c" },
      { name: "Silver", hex: "#e8e8e8" },
      { name: "Sky Blue", hex: "#5ac8fa" },
      { name: "Green", hex: "#34c759" },
      { name: "Pink", hex: "#ff9ff3" },
    ],
  },
  // ——— Accessories ———
  {
    slug: "magic-keyboard-ipad-pro",
    name: "Magic Keyboard for iPad Pro 13\"",
    categorySlug: "accessories",
    description: "Floating design. Built-in trackpad. Backlit keys. USB-C pass-through charging. Folds into a protective cover.",
    shortDescription: "Floating. Trackpad. Backlit. USB-C.",
    price: 349,
    currency: "USD",
    badge: "Premium",
    inStock: true,
    rating: 4.7,
    reviewCount: 654,
    images: [U("1583394838336-acd977736f90")],
    specs: [
      { label: "Compatibility", value: "iPad Pro 13\" (M4)" },
      { label: "Features", value: "Scissor mechanism; backlit keys; multi-touch trackpad" },
      { label: "Port", value: "USB-C pass-through" },
    ],
    colors: [{ name: "White", hex: "#f5f5f5" }],
  },
  {
    slug: "usb-c-to-usb-c-2m",
    name: "USB-C to USB-C Cable (2m)",
    categorySlug: "accessories",
    description: "Charge and sync Mac, iPad, iPhone 15. 2 meters. USB 2 data transfer.",
    shortDescription: "2m. USB-C. Charge & sync.",
    price: 29,
    currency: "USD",
    badge: "Premium",
    inStock: true,
    rating: 4.7,
    reviewCount: 6543,
    images: [U("1609091839311-d5365f9ff1c5")],
    specs: [
      { label: "Length", value: "2 m" },
      { label: "Connector", value: "USB-C to USB-C" },
      { label: "Data", value: "USB 2 (480 Mb/s)" },
    ],
    colors: [{ name: "White", hex: "#f5f5f5" }],
  },
  {
    slug: "67w-usb-c-adapter",
    name: "67W USB-C Power Adapter",
    categorySlug: "accessories",
    description: "Fast charge for 14\" MacBook Pro and MacBook Air. Compact design. USB-C.",
    shortDescription: "67W. MacBook Pro / Air.",
    price: 79,
    currency: "USD",
    badge: "Premium",
    inStock: true,
    rating: 4.6,
    reviewCount: 2156,
    images: [U("1609091839311-d5365f9ff1c5")],
    specs: [
      { label: "Output", value: "67W USB-C" },
      { label: "Compatibility", value: "14\" MacBook Pro, MacBook Air M2/M3" },
    ],
    colors: [{ name: "White", hex: "#f5f5f5" }],
  },
  // ——— المزيد من iPhone ———
  {
    slug: "iphone-16-plus",
    name: "iPhone 16 Plus",
    categorySlug: "iphone",
    description: "A18 chip. 6.7-inch Super Retina XDR. 48MP Main. Larger screen. Aluminum. Five colors.",
    shortDescription: "6.7\" Super Retina XDR. A18. 48MP.",
    price: 899,
    currency: "USD",
    badge: "New",
    inStock: true,
    rating: 4.7,
    reviewCount: 1823,
    images: [U("1592286927505-d6d2a7a029c7")],
    specs: [
      { label: "Display", value: "6.7\" Super Retina XDR, 60Hz, 2000 nits peak" },
      { label: "Chip", value: "A18 — 6-core CPU, 6-core GPU" },
      { label: "Camera", value: "48MP Main, 12MP Ultra Wide; 4K video" },
      { label: "Storage", value: "128GB / 256GB / 512GB" },
      { label: "Durability", value: "IP68; Ceramic Shield" },
    ],
    colors: [
      { name: "Black", hex: "#1d1d1f" },
      { name: "White", hex: "#fbfbfd" },
      { name: "Blue", hex: "#4a90d9" },
      { name: "Green", hex: "#34c759" },
      { name: "Pink", hex: "#ff9ff3" },
    ],
  },
  {
    slug: "iphone-15-plus",
    name: "iPhone 15 Plus",
    categorySlug: "iphone",
    description: "A16 Bionic. 6.7-inch Super Retina XDR. 48MP Main. Dynamic Island. USB-C.",
    shortDescription: "6.7\" Super Retina XDR. A16. 48MP.",
    price: 799,
    currency: "USD",
    badge: "Best Seller",
    inStock: true,
    rating: 4.6,
    reviewCount: 2103,
    images: [U("1592286927505-d6d2a7a029c7")],
    specs: [
      { label: "Display", value: "6.7\" Super Retina XDR, 60Hz, 2000 nits peak" },
      { label: "Chip", value: "A16 Bionic" },
      { label: "Camera", value: "48MP Main, 12MP Ultra Wide" },
      { label: "Storage", value: "128GB / 256GB / 512GB" },
      { label: "Durability", value: "IP68" },
    ],
    colors: [
      { name: "Black", hex: "#1d1d1f" },
      { name: "Blue", hex: "#4a90d9" },
      { name: "Green", hex: "#34c759" },
      { name: "Pink", hex: "#ff9ff3" },
      { name: "Yellow", hex: "#ffd60a" },
    ],
  },
  {
    slug: "iphone-15-pro",
    name: "iPhone 15 Pro",
    categorySlug: "iphone",
    description: "A17 Pro. 6.1-inch Super Retina XDR. 48MP Main. Titanium. Action button.",
    shortDescription: "6.1\" Super Retina XDR. A17 Pro. Titanium.",
    price: 899,
    currency: "USD",
    badge: "Pro",
    inStock: true,
    rating: 4.8,
    reviewCount: 1923,
    images: [U("1510557880182-3d4d3cba35a5")],
    specs: [
      { label: "Display", value: "6.1\" Super Retina XDR OLED, ProMotion 120Hz" },
      { label: "Chip", value: "A17 Pro" },
      { label: "Camera", value: "48MP Main, 12MP Ultra Wide, 12MP 3x Telephoto" },
      { label: "Storage", value: "128GB / 256GB / 512GB / 1TB" },
      { label: "Durability", value: "IP68; Titanium" },
    ],
    colors: [
      { name: "Black Titanium", hex: "#1a1a1a" },
      { name: "White Titanium", hex: "#f5f5f0" },
      { name: "Natural Titanium", hex: "#c4b8a8" },
      { name: "Blue Titanium", hex: "#5e7fa5" },
    ],
  },
  {
    slug: "iphone-14",
    name: "iPhone 14",
    categorySlug: "iphone",
    description: "A15 Bionic. 6.1-inch Super Retina XDR. 12MP dual camera. Crash Detection. Emergency SOS via satellite.",
    shortDescription: "A15. 6.1\" Super Retina. 12MP dual.",
    price: 599,
    currency: "USD",
    badge: "Value",
    inStock: true,
    rating: 4.5,
    reviewCount: 3200,
    images: [U("1592750475338-74b7b21085ab")],
    specs: [
      { label: "Display", value: "6.1\" Super Retina XDR, 60Hz" },
      { label: "Chip", value: "A15 Bionic" },
      { label: "Camera", value: "12MP Main, 12MP Ultra Wide" },
      { label: "Storage", value: "128GB / 256GB / 512GB" },
      { label: "Durability", value: "IP68" },
    ],
    colors: [
      { name: "Midnight", hex: "#1e1e2e" },
      { name: "Starlight", hex: "#f5e6d3" },
      { name: "Blue", hex: "#4a90d9" },
      { name: "Purple", hex: "#bf5af2" },
      { name: "Red", hex: "#ff3b30" },
    ],
  },
  {
    slug: "iphone-se-3rd-gen",
    name: "iPhone SE (3rd generation)",
    categorySlug: "iphone",
    description: "A15 Bionic. 4.7-inch Retina HD. Touch ID. Affordable iPhone. 5G.",
    shortDescription: "A15. 4.7\" Retina. Touch ID. 5G.",
    price: 429,
    currency: "USD",
    badge: "Value",
    inStock: true,
    rating: 4.4,
    reviewCount: 4102,
    images: [U("1592750475338-74b7b21085ab")],
    specs: [
      { label: "Display", value: "4.7\" Retina HD, 60Hz" },
      { label: "Chip", value: "A15 Bionic" },
      { label: "Camera", value: "12MP single camera" },
      { label: "Storage", value: "64GB / 128GB / 256GB" },
      { label: "Touch ID", value: "Built-in Home button" },
    ],
    colors: [
      { name: "Midnight", hex: "#1e1e2e" },
      { name: "Starlight", hex: "#f5e6d3" },
      { name: "Red", hex: "#ff3b30" },
    ],
  },
  // ——— المزيد من MacBook و Mac ———
  {
    slug: "macbook-air-15-m3",
    name: "MacBook Air 15\" (M3, 2024)",
    categorySlug: "macbook-m3",
    subcategory: "Air 15\"",
    description: "15.3-inch Liquid Retina. M3 chip. Up to 18 hours battery. Thin and light. Six speakers.",
    shortDescription: "M3. 15.3\" Liquid Retina. 18h.",
    price: 1299,
    currency: "USD",
    badge: "New",
    inStock: true,
    rating: 4.8,
    reviewCount: 892,
    images: [U("1611186871348-b1ce696e52c9")],
    specs: [
      { label: "Model Year", value: "2024" },
      { label: "Chip", value: "M3 — 8-core CPU, 10-core GPU" },
      { label: "Display", value: "15.3\" Liquid Retina — 2880×1864, 224 ppi, 500 nits" },
      { label: "Memory", value: "8GB or 16GB unified memory" },
      { label: "Storage", value: "256GB, 512GB, or 1TB SSD" },
      { label: "Battery", value: "Up to 18 hours" },
      { label: "Weight", value: "1.51 kg (3.3 lb)" },
    ],
    colors: [
      { name: "Midnight", hex: "#1e1e2e" },
      { name: "Starlight", hex: "#f5e6d3" },
      { name: "Space Gray", hex: "#53525c" },
      { name: "Silver", hex: "#e8e8e8" },
    ],
  },
  {
    slug: "mac-mini-m2",
    name: "Mac mini (M2, 2023)",
    categorySlug: "mac-mini",
    subcategory: "M2 / M2 Pro",
    description: "M2 or M2 Pro. Compact desktop. 8GB–24GB memory. 256GB–2TB SSD. Silent. Ports: Thunderbolt 4, HDMI, Gigabit Ethernet.",
    shortDescription: "M2/M2 Pro. Compact. Silent.",
    price: 599,
    currency: "USD",
    badge: "Value",
    inStock: true,
    rating: 4.8,
    reviewCount: 2341,
    images: [U("1527443224154-c4a3942d3acf")],
    specs: [
      { label: "Model Year", value: "2023" },
      { label: "Chip", value: "M2 — 8-core CPU, 10-core GPU; or M2 Pro" },
      { label: "Memory", value: "8GB–24GB unified memory" },
      { label: "Storage", value: "256GB–2TB SSD" },
      { label: "Ports", value: "2× Thunderbolt 4, HDMI, 2× USB-A, Gigabit Ethernet, 3.5mm" },
    ],
    colors: [{ name: "Silver", hex: "#e8e8e8" }],
  },
  {
    slug: "mac-studio-m2-max",
    name: "Mac Studio (M2 Max / M2 Ultra, 2023)",
    categorySlug: "mac-studio",
    subcategory: "M2 Max / M2 Ultra",
    description: "M2 Max or M2 Ultra. Pro desktop. Compact. Up to 192GB memory. Multiple Thunderbolt 4, HDMI, 10Gb Ethernet.",
    shortDescription: "M2 Max/Ultra. Pro desktop.",
    price: 1999,
    currency: "USD",
    badge: "Pro",
    inStock: true,
    rating: 4.9,
    reviewCount: 456,
    images: [U("1527443224154-c4a3942d3acf")],
    specs: [
      { label: "Model Year", value: "2023" },
      { label: "Chip", value: "M2 Max — 12-core CPU, 30-core GPU; or M2 Ultra" },
      { label: "Memory", value: "32GB–192GB unified memory" },
      { label: "Storage", value: "512GB–8TB SSD" },
      { label: "Ports", value: "4× Thunderbolt 4, 2× USB-A, HDMI, 10Gb Ethernet, 3.5mm" },
    ],
    colors: [{ name: "Silver", hex: "#e8e8e8" }],
  },
  // ——— MacBook Air M1, M2 ———
  {
    slug: "macbook-air-m1-13",
    name: "MacBook Air 13\" (M1, 2020)",
    categorySlug: "macbook-m1",
    subcategory: "Air 13\"",
    description: "13.3-inch Retina. M1 chip. Up to 18 hours battery. First Apple Silicon MacBook Air. Gold, Silver, Space Gray.",
    shortDescription: "M1. 13.3\" Retina. 18h. أول Air بشيب أبل.",
    price: 999,
    currency: "USD",
    badge: "Value",
    inStock: true,
    rating: 4.8,
    reviewCount: 5200,
    images: [U("1611186871348-b1ce696e52c9")],
    specs: [
      { label: "Model Year", value: "2020" },
      { label: "Chip", value: "M1 — 8-core CPU, 8-core GPU, 16-core Neural Engine" },
      { label: "Display", value: "13.3\" Retina — 2560×1600, 227 ppi, 400 nits" },
      { label: "Memory", value: "8GB or 16GB unified memory" },
      { label: "Storage", value: "256GB, 512GB, or 1TB SSD" },
      { label: "Battery", value: "Up to 18 hours" },
      { label: "Weight", value: "1.29 kg (2.8 lb)" },
    ],
    colors: [
      { name: "Gold", hex: "#d4a574" },
      { name: "Silver", hex: "#e8e8e8" },
      { name: "Space Gray", hex: "#53525c" },
    ],
  },
  {
    slug: "macbook-air-m2-13",
    name: "MacBook Air 13\" (M2, 2022)",
    categorySlug: "macbook-m2",
    subcategory: "Air 13\"",
    description: "13.6-inch Liquid Retina. M2 chip. MagSafe. Up to 18 hours. Midnight, Starlight, Space Gray, Silver.",
    shortDescription: "M2. 13.6\" Liquid Retina. MagSafe. 18h.",
    price: 1099,
    currency: "USD",
    badge: "Best Seller",
    inStock: true,
    rating: 4.8,
    reviewCount: 3100,
    images: [U("1611186871348-b1ce696e52c9")],
    specs: [
      { label: "Model Year", value: "2022" },
      { label: "Chip", value: "M2 — 8-core CPU, 10-core GPU, 16-core Neural Engine" },
      { label: "Display", value: "13.6\" Liquid Retina — 2560×1664, 224 ppi, 500 nits" },
      { label: "Memory", value: "8GB or 16GB unified memory" },
      { label: "Storage", value: "256GB, 512GB, or 1TB SSD" },
      { label: "Battery", value: "Up to 18 hours; MagSafe 3" },
      { label: "Weight", value: "1.24 kg (2.7 lb)" },
    ],
    colors: [
      { name: "Midnight", hex: "#1e1e2e" },
      { name: "Starlight", hex: "#f5e6d3" },
      { name: "Space Gray", hex: "#53525c" },
      { name: "Silver", hex: "#e8e8e8" },
    ],
  },
  {
    slug: "macbook-air-m2-15",
    name: "MacBook Air 15\" (M2, 2023)",
    categorySlug: "macbook-m2",
    subcategory: "Air 15\"",
    description: "15.3-inch Liquid Retina. M2 chip. Up to 18 hours. Thin and light. Six speakers. Larger display.",
    shortDescription: "M2. 15.3\" Liquid Retina. 18h.",
    price: 1299,
    currency: "USD",
    badge: "Premium",
    inStock: true,
    rating: 4.8,
    reviewCount: 1200,
    images: [U("1611186871348-b1ce696e52c9")],
    specs: [
      { label: "Model Year", value: "2023" },
      { label: "Chip", value: "M2 — 8-core CPU, 10-core GPU" },
      { label: "Display", value: "15.3\" Liquid Retina — 2880×1864, 224 ppi, 500 nits" },
      { label: "Memory", value: "8GB or 16GB unified memory" },
      { label: "Storage", value: "256GB, 512GB, or 1TB SSD" },
      { label: "Battery", value: "Up to 18 hours" },
      { label: "Weight", value: "1.51 kg (3.3 lb)" },
    ],
    colors: [
      { name: "Midnight", hex: "#1e1e2e" },
      { name: "Starlight", hex: "#f5e6d3" },
      { name: "Space Gray", hex: "#53525c" },
      { name: "Silver", hex: "#e8e8e8" },
    ],
  },
  // ——— MacBook Pro M1, M2, M3 ———
  {
    slug: "macbook-pro-13-m1",
    name: "MacBook Pro 13\" (M1, 2020)",
    categorySlug: "macbook-m1",
    subcategory: "Pro 13\"",
    description: "13.3-inch Retina. M1 chip. Touch Bar. Up to 20 hours battery. First Apple Silicon MacBook Pro.",
    shortDescription: "M1. 13.3\" Retina. Touch Bar. 20h.",
    price: 1299,
    currency: "USD",
    badge: "Value",
    inStock: true,
    rating: 4.7,
    reviewCount: 4100,
    images: [U("1517336714731-489689fd1ca8")],
    specs: [
      { label: "Model Year", value: "2020" },
      { label: "Chip", value: "M1 — 8-core CPU, 8-core GPU" },
      { label: "Display", value: "13.3\" Retina — 2560×1600, 227 ppi, 500 nits" },
      { label: "Memory", value: "8GB or 16GB unified memory" },
      { label: "Storage", value: "256GB, 512GB, or 1TB SSD" },
      { label: "Battery", value: "Up to 20 hours; Touch Bar" },
      { label: "Weight", value: "1.4 kg (3.1 lb)" },
    ],
    colors: [{ name: "Silver", hex: "#e8e8e8" }, { name: "Space Gray", hex: "#53525c" }],
  },
  {
    slug: "macbook-pro-14-m1-pro",
    name: "MacBook Pro 14\" (M1 Pro, 2021)",
    categorySlug: "macbook-m1",
    subcategory: "Pro 14\"",
    description: "14.2-inch Liquid Retina XDR. M1 Pro or M1 Max. ProMotion 120Hz. Up to 17 hours. Notch. SDXC, HDMI.",
    shortDescription: "M1 Pro/Max. 14.2\" XDR. ProMotion.",
    price: 1999,
    currency: "USD",
    badge: "Pro",
    inStock: true,
    rating: 4.9,
    reviewCount: 2100,
    images: [U("1517336714731-489689fd1ca8")],
    specs: [
      { label: "Model Year", value: "2021" },
      { label: "Chip", value: "M1 Pro — 8/10-core CPU, 14/16-core GPU; or M1 Max" },
      { label: "Display", value: "14.2\" Liquid Retina XDR — 3024×1964, 254 ppi, ProMotion 120Hz, 1000 nits" },
      { label: "Memory", value: "16GB–64GB unified memory" },
      { label: "Storage", value: "512GB–2TB SSD" },
      { label: "Battery", value: "Up to 17 hours; MagSafe 3" },
      { label: "Ports", value: "3× Thunderbolt 4, HDMI, SDXC, MagSafe 3, 3.5mm" },
    ],
    colors: [
      { name: "Space Gray", hex: "#53525c" },
      { name: "Silver", hex: "#e8e8e8" },
    ],
  },
  {
    slug: "macbook-pro-16-m1-pro",
    name: "MacBook Pro 16\" (M1 Pro / M1 Max, 2021)",
    categorySlug: "macbook-m1",
    subcategory: "Pro 16\"",
    description: "16.2-inch Liquid Retina XDR. M1 Pro or M1 Max. ProMotion. Up to 21 hours. Pro performance.",
    shortDescription: "M1 Pro/Max. 16.2\" XDR. 21h.",
    price: 2499,
    currency: "USD",
    badge: "Pro",
    inStock: true,
    rating: 4.9,
    reviewCount: 1800,
    images: [U("1611186871348-b1ce696e52c9")],
    specs: [
      { label: "Model Year", value: "2021" },
      { label: "Chip", value: "M1 Pro — 10-core CPU, 16-core GPU; or M1 Max — 10-core CPU, 32-core GPU" },
      { label: "Display", value: "16.2\" Liquid Retina XDR — 3456×2234, 254 ppi, ProMotion 120Hz, 1000 nits" },
      { label: "Memory", value: "16GB–64GB (M1 Pro) or 32GB–64GB (M1 Max)" },
      { label: "Storage", value: "512GB–2TB SSD" },
      { label: "Battery", value: "Up to 21 hours; 100Wh; 140W MagSafe 3" },
      { label: "Ports", value: "3× Thunderbolt 4, HDMI, SDXC, MagSafe 3, 3.5mm" },
    ],
    colors: [
      { name: "Space Gray", hex: "#53525c" },
      { name: "Silver", hex: "#e8e8e8" },
    ],
  },
  {
    slug: "macbook-pro-14-m2-pro",
    name: "MacBook Pro 14\" (M2 Pro, 2023)",
    categorySlug: "macbook-m2",
    subcategory: "Pro 14\"",
    description: "14.2-inch Liquid Retina XDR. M2 Pro or M2 Max. ProMotion. Up to 17 hours. Space Black or Silver.",
    shortDescription: "M2 Pro/Max. 14.2\" XDR. 17h.",
    price: 1999,
    currency: "USD",
    badge: "Pro",
    inStock: true,
    rating: 4.9,
    reviewCount: 950,
    images: [U("1517336714731-489689fd1ca8")],
    specs: [
      { label: "Model Year", value: "2023" },
      { label: "Chip", value: "M2 Pro — 10/12-core CPU, 16/19-core GPU; or M2 Max" },
      { label: "Display", value: "14.2\" Liquid Retina XDR — 3024×1964, 254 ppi, ProMotion 120Hz" },
      { label: "Memory", value: "16GB–96GB unified memory" },
      { label: "Storage", value: "512GB–2TB SSD" },
      { label: "Battery", value: "Up to 17 hours; MagSafe 3" },
      { label: "Ports", value: "3× Thunderbolt 4, HDMI, SDXC, MagSafe 3, 3.5mm" },
    ],
    colors: [
      { name: "Space Black", hex: "#1a1a1a" },
      { name: "Silver", hex: "#e8e8e8" },
    ],
  },
  {
    slug: "macbook-pro-16-m2-pro",
    name: "MacBook Pro 16\" (M2 Pro / M2 Max, 2023)",
    categorySlug: "macbook-m2",
    subcategory: "Pro 16\"",
    description: "16.2-inch Liquid Retina XDR. M2 Pro or M2 Max. ProMotion. Up to 22 hours. Pro performance.",
    shortDescription: "M2 Pro/Max. 16.2\" XDR. 22h.",
    price: 2499,
    currency: "USD",
    badge: "Pro",
    inStock: true,
    rating: 4.9,
    reviewCount: 820,
    images: [U("1611186871348-b1ce696e52c9")],
    specs: [
      { label: "Model Year", value: "2023" },
      { label: "Chip", value: "M2 Pro — 12-core CPU, 19-core GPU; or M2 Max — 12-core CPU, 38-core GPU" },
      { label: "Display", value: "16.2\" Liquid Retina XDR — 3456×2234, 254 ppi, ProMotion 120Hz" },
      { label: "Memory", value: "16GB–96GB unified memory" },
      { label: "Storage", value: "512GB–2TB SSD" },
      { label: "Battery", value: "Up to 22 hours; 100Wh; 140W MagSafe 3" },
      { label: "Ports", value: "3× Thunderbolt 4, HDMI, SDXC, MagSafe 3, 3.5mm" },
    ],
    colors: [
      { name: "Space Black", hex: "#1a1a1a" },
      { name: "Silver", hex: "#e8e8e8" },
    ],
  },
  {
    slug: "macbook-pro-14-m3",
    name: "MacBook Pro 14\" (M3, 2023)",
    categorySlug: "macbook-m3",
    subcategory: "Pro 14\"",
    description: "14.2-inch Liquid Retina XDR. M3 chip. Up to 22 hours. Space Black or Silver. Entry Pro.",
    shortDescription: "M3. 14.2\" XDR. 22h.",
    price: 1599,
    currency: "USD",
    badge: "Pro",
    inStock: true,
    rating: 4.8,
    reviewCount: 1100,
    images: [U("1517336714731-489689fd1ca8")],
    specs: [
      { label: "Model Year", value: "2023" },
      { label: "Chip", value: "M3 — 8-core CPU, 10-core GPU" },
      { label: "Display", value: "14.2\" Liquid Retina XDR — 3024×1964, 254 ppi, ProMotion 120Hz" },
      { label: "Memory", value: "8GB or 16GB unified memory (up to 24GB)" },
      { label: "Storage", value: "512GB or 1TB SSD (up to 2TB)" },
      { label: "Battery", value: "Up to 22 hours; MagSafe 3" },
      { label: "Ports", value: "3× Thunderbolt 4, HDMI, SDXC, MagSafe 3, 3.5mm" },
    ],
    colors: [
      { name: "Space Black", hex: "#1a1a1a" },
      { name: "Silver", hex: "#e8e8e8" },
    ],
  },
  {
    slug: "macbook-pro-16-m3-pro",
    name: "MacBook Pro 16\" (M3 Pro / M3 Max, 2023)",
    categorySlug: "macbook-m3",
    subcategory: "Pro 16\"",
    description: "16.2-inch Liquid Retina XDR. M3 Pro or M3 Max. ProMotion. Up to 22 hours. Pro performance.",
    shortDescription: "M3 Pro/Max. 16.2\" XDR. 22h.",
    price: 2499,
    currency: "USD",
    badge: "Pro",
    inStock: true,
    rating: 4.9,
    reviewCount: 720,
    images: [U("1611186871348-b1ce696e52c9")],
    specs: [
      { label: "Model Year", value: "2023" },
      { label: "Chip", value: "M3 Pro — 11/12-core CPU, 14/18-core GPU; or M3 Max — 14/16-core CPU, 30/40-core GPU" },
      { label: "Display", value: "16.2\" Liquid Retina XDR — 3456×2234, 254 ppi, ProMotion 120Hz" },
      { label: "Memory", value: "18GB–128GB unified memory" },
      { label: "Storage", value: "512GB–2TB SSD" },
      { label: "Battery", value: "Up to 22 hours; 100Wh; 140W MagSafe 3" },
      { label: "Ports", value: "3× Thunderbolt 4, HDMI, SDXC, MagSafe 3, 3.5mm" },
    ],
    colors: [
      { name: "Space Black", hex: "#1a1a1a" },
      { name: "Silver", hex: "#e8e8e8" },
    ],
  },
  {
    slug: "macbook-air-m4-13",
    name: "MacBook Air 13\" (M4, 2025)",
    categorySlug: "macbook-m4",
    subcategory: "Air 13\"",
    description: "13.6-inch Liquid Retina. M4 chip. Up to 18 hours. Thinner. Midnight, Starlight, Space Gray, Silver.",
    shortDescription: "M4. 13.6\" Liquid Retina. 18h.",
    price: 1099,
    currency: "USD",
    badge: "New",
    inStock: true,
    rating: 4.8,
    reviewCount: 420,
    images: [U("1611186871348-b1ce696e52c9")],
    specs: [
      { label: "Model Year", value: "2025" },
      { label: "Chip", value: "M4 — 8-core CPU, 10-core GPU, 16-core Neural Engine" },
      { label: "Display", value: "13.6\" Liquid Retina — 2560×1664, 224 ppi, 500 nits" },
      { label: "Memory", value: "8GB or 16GB unified memory" },
      { label: "Storage", value: "256GB, 512GB, or 1TB SSD" },
      { label: "Battery", value: "Up to 18 hours; 52.6Wh" },
      { label: "Weight", value: "1.24 kg (2.7 lb)" },
    ],
    colors: [
      { name: "Midnight", hex: "#1e1e2e" },
      { name: "Starlight", hex: "#f5e6d3" },
      { name: "Space Gray", hex: "#53525c" },
      { name: "Silver", hex: "#e8e8e8" },
    ],
  },
  // ——— iMac 24" M1، Mac mini M1، Mac Studio M1، Mac Pro ———
  {
    slug: "imac-24-m1",
    name: "iMac 24\" (M1, 2021)",
    categorySlug: "imac",
    subcategory: "24\" M1",
    description: "24-inch 4.5K Retina. M1 chip. Seven colors. All-in-one. 1080p FaceTime. First Apple Silicon iMac.",
    shortDescription: "M1. 24\" 4.5K. Seven colors. 2021.",
    price: 1299,
    currency: "USD",
    badge: "Value",
    inStock: true,
    rating: 4.8,
    reviewCount: 3200,
    images: [U("1527443224154-c4a3942d3acf")],
    specs: [
      { label: "Model Year", value: "2021" },
      { label: "Chip", value: "M1 — 8-core CPU, 8-core GPU" },
      { label: "Display", value: "24\" 4.5K Retina — 4480×2520, 218 ppi, 500 nits, P3" },
      { label: "Memory", value: "8GB unified memory (16GB configurable)" },
      { label: "Storage", value: "256GB / 512GB / 1TB SSD" },
      { label: "Camera", value: "1080p FaceTime HD camera" },
      { label: "Audio", value: "Six-speaker system with Spatial Audio" },
    ],
    colors: [
      { name: "Blue", hex: "#4a90d9" },
      { name: "Green", hex: "#34c759" },
      { name: "Pink", hex: "#ff9ff3" },
      { name: "Silver", hex: "#e8e8e8" },
    ],
  },
  {
    slug: "mac-mini-m1",
    name: "Mac mini (M1, 2020)",
    categorySlug: "mac-mini",
    subcategory: "M1",
    description: "M1 chip. Compact desktop. 8GB or 16GB memory. 256GB–2TB SSD. Silent. First Apple Silicon Mac mini.",
    shortDescription: "M1. Compact. Silent. 2020.",
    price: 699,
    currency: "USD",
    badge: "Value",
    inStock: true,
    rating: 4.8,
    reviewCount: 4500,
    images: [U("1527443224154-c4a3942d3acf")],
    specs: [
      { label: "Model Year", value: "2020" },
      { label: "Chip", value: "M1 — 8-core CPU, 8-core GPU" },
      { label: "Memory", value: "8GB or 16GB unified memory" },
      { label: "Storage", value: "256GB–2TB SSD" },
      { label: "Ports", value: "2× Thunderbolt 4, HDMI, 2× USB-A, Gigabit Ethernet, 3.5mm" },
    ],
    colors: [{ name: "Silver", hex: "#e8e8e8" }],
  },
  {
    slug: "mac-studio-m1-max",
    name: "Mac Studio (M1 Max, 2022)",
    categorySlug: "mac-studio",
    subcategory: "M1 Max",
    description: "M1 Max. Pro desktop. Compact. 32GB–64GB memory. Multiple Thunderbolt 4, HDMI, 10Gb Ethernet.",
    shortDescription: "M1 Max. Pro desktop. 2022.",
    price: 1999,
    currency: "USD",
    badge: "Pro",
    inStock: true,
    rating: 4.9,
    reviewCount: 890,
    images: [U("1527443224154-c4a3942d3acf")],
    specs: [
      { label: "Model Year", value: "2022" },
      { label: "Chip", value: "M1 Max — 10-core CPU, 24-core GPU or 32-core GPU" },
      { label: "Memory", value: "32GB or 64GB unified memory" },
      { label: "Storage", value: "512GB–2TB SSD" },
      { label: "Ports", value: "4× Thunderbolt 4, 2× USB-A, HDMI, 10Gb Ethernet, 3.5mm" },
    ],
    colors: [{ name: "Silver", hex: "#e8e8e8" }],
  },
  {
    slug: "mac-studio-m1-ultra",
    name: "Mac Studio (M1 Ultra, 2022)",
    categorySlug: "mac-studio",
    subcategory: "M1 Ultra",
    description: "M1 Ultra. Pro desktop. Up to 128GB memory. Dual M1 Max. For demanding workflows.",
    shortDescription: "M1 Ultra. Pro desktop. 2022.",
    price: 3999,
    currency: "USD",
    badge: "Pro",
    inStock: true,
    rating: 4.9,
    reviewCount: 456,
    images: [U("1527443224154-c4a3942d3acf")],
    specs: [
      { label: "Model Year", value: "2022" },
      { label: "Chip", value: "M1 Ultra — 20-core CPU, 48-core or 64-core GPU" },
      { label: "Memory", value: "64GB or 128GB unified memory" },
      { label: "Storage", value: "1TB–8TB SSD" },
      { label: "Ports", value: "4× Thunderbolt 4, 2× USB-A, HDMI, 10Gb Ethernet, 3.5mm" },
    ],
    colors: [{ name: "Silver", hex: "#e8e8e8" }],
  },
  {
    slug: "mac-pro-m2-ultra",
    name: "Mac Pro (M2 Ultra, 2023)",
    categorySlug: "mac-pro",
    subcategory: "M2 Ultra",
    description: "M2 Ultra. Workstation. PCIe expansion. Up to 192GB memory. 8× Thunderbolt 4, 6× PCIe slots.",
    shortDescription: "M2 Ultra. Workstation. PCIe. 2023.",
    price: 6999,
    currency: "USD",
    badge: "Pro",
    inStock: true,
    rating: 4.9,
    reviewCount: 234,
    images: [U("1527443224154-c4a3942d3acf")],
    specs: [
      { label: "Model Year", value: "2023" },
      { label: "Chip", value: "M2 Ultra — 24-core CPU, 60-core or 76-core GPU" },
      { label: "Memory", value: "64GB–192GB unified memory" },
      { label: "Storage", value: "1TB–8TB SSD" },
      { label: "Expansion", value: "6× PCIe Gen 4 slots; 8× Thunderbolt 4" },
      { label: "Ports", value: "2× USB-A, 2× 10Gb Ethernet, 3.5mm, HDMI" },
    ],
    colors: [{ name: "Silver", hex: "#e8e8e8" }],
  },
  // ——— المزيد من iPad ———
  {
    slug: "ipad-pro-11-m4",
    name: "iPad Pro 11\" (M4, 2024)",
    categorySlug: "ipad",
    description: "M4 chip. 11-inch Tandem OLED. Ultra-thin. Pro cameras. Apple Pencil Pro.",
    shortDescription: "M4. 11\" Tandem OLED. Ultra-thin.",
    price: 999,
    currency: "USD",
    badge: "New",
    inStock: true,
    rating: 4.9,
    reviewCount: 534,
    images: [U("1544244015-0df4b3ffc6b0")],
    specs: [
      { label: "Chip", value: "M4 — 10-core CPU, 10-core GPU" },
      { label: "Display", value: "11\" Tandem OLED — 2420×1668, 264 ppi, ProMotion 120Hz" },
      { label: "Storage", value: "256GB / 512GB / 1TB / 2TB" },
      { label: "Thickness", value: "5.3 mm" },
    ],
    colors: [
      { name: "Space Black", hex: "#1a1a1a" },
      { name: "Silver", hex: "#e8e8e8" },
    ],
  },
  {
    slug: "ipad-10th-gen",
    name: "iPad (10th generation)",
    categorySlug: "ipad",
    description: "10.9-inch Liquid Retina. A14 Bionic. USB-C. Landscape 12MP front camera. Four colors.",
    shortDescription: "10.9\" Liquid Retina. A14. USB-C.",
    price: 349,
    currency: "USD",
    badge: "Best Seller",
    inStock: true,
    rating: 4.6,
    reviewCount: 3201,
    images: [U("1544244015-0df4b3ffc6b0")],
    specs: [
      { label: "Chip", value: "A14 Bionic" },
      { label: "Display", value: "10.9\" Liquid Retina — 2360×1640, 264 ppi" },
      { label: "Storage", value: "64GB or 256GB" },
      { label: "Camera", value: "12MP front (landscape); 12MP rear" },
    ],
    colors: [
      { name: "Blue", hex: "#4a90d9" },
      { name: "Pink", hex: "#ff9ff3" },
      { name: "Yellow", hex: "#ffd60a" },
      { name: "Silver", hex: "#e8e8e8" },
    ],
  },
  {
    slug: "ipad-mini-6",
    name: "iPad mini (6th generation)",
    categorySlug: "ipad",
    description: "8.3-inch Liquid Retina. A15 Bionic. USB-C. Touch ID in top button. Compact.",
    shortDescription: "8.3\" Liquid Retina. A15. Compact.",
    price: 499,
    currency: "USD",
    badge: "Premium",
    inStock: true,
    rating: 4.7,
    reviewCount: 1823,
    images: [U("1544244015-0df4b3ffc6b0")],
    specs: [
      { label: "Chip", value: "A15 Bionic" },
      { label: "Display", value: "8.3\" Liquid Retina — 2266×1488, 326 ppi" },
      { label: "Storage", value: "64GB or 256GB" },
      { label: "Touch ID", value: "In top button" },
    ],
    colors: [
      { name: "Space Gray", hex: "#53525c" },
      { name: "Pink", hex: "#ff9ff3" },
      { name: "Purple", hex: "#bf5af2" },
      { name: "Starlight", hex: "#f5e6d3" },
    ],
  },
  // ——— المزيد من Apple Watch ———
  {
    slug: "apple-watch-se-2",
    name: "Apple Watch SE (2nd generation)",
    categorySlug: "watch",
    description: "40mm or 44mm. Retina display. S8 SiP. Crash Detection. Fall Detection. 18-hour battery. Affordable.",
    shortDescription: "40/44mm. S8. Crash Detection. 18h.",
    price: 249,
    currency: "USD",
    badge: "Value",
    inStock: true,
    rating: 4.6,
    reviewCount: 2891,
    images: [U("1434493789847-2f02dc6ca35d")],
    specs: [
      { label: "Case", value: "40mm or 44mm; 50m water resistant" },
      { label: "Display", value: "Retina LTPO OLED" },
      { label: "Chip", value: "S8 SiP" },
      { label: "Battery", value: "Up to 18 hours" },
      { label: "Features", value: "Crash Detection; Fall Detection; Heart rate; Sleep" },
    ],
    colors: [
      { name: "Midnight", hex: "#1e1e2e" },
      { name: "Starlight", hex: "#f5e6d3" },
      { name: "Silver", hex: "#e8e8e8" },
    ],
  },
  // ——— المزيد من AirPods ———
  {
    slug: "airpods-3rd-gen",
    name: "AirPods (3rd generation)",
    categorySlug: "airpods",
    description: "Personalized Spatial Audio. Adaptive EQ. Sweat and water resistant. Up to 6 hours. MagSafe Charging Case.",
    shortDescription: "Spatial Audio. 6h. MagSafe case.",
    price: 169,
    currency: "USD",
    badge: "Best Seller",
    inStock: true,
    rating: 4.7,
    reviewCount: 5203,
    images: [U("1587523459887-e669248cf666")],
    specs: [
      { label: "Audio", value: "Personalized Spatial Audio; Adaptive EQ" },
      { label: "Battery", value: "Up to 6 hours; 30 hours with case" },
      { label: "Case", value: "MagSafe; Lightning" },
      { label: "Resistance", value: "Sweat and water resistant (IPX4)" },
    ],
    colors: [{ name: "White", hex: "#f5f5f5" }],
  },
  {
    slug: "airpods-2nd-gen",
    name: "AirPods (2nd generation)",
    categorySlug: "airpods",
    description: "Classic design. H1 chip. Up to 5 hours. Charging case or Wireless Charging Case. Siri.",
    shortDescription: "H1. 5h. Wireless Charging Case.",
    price: 129,
    currency: "USD",
    badge: "Value",
    inStock: true,
    rating: 4.5,
    reviewCount: 8102,
    images: [U("1587523459887-e669248cf666")],
    specs: [
      { label: "Chip", value: "H1" },
      { label: "Battery", value: "Up to 5 hours; 24 hours with case" },
      { label: "Case", value: "Lightning or Wireless Charging Case" },
    ],
    colors: [{ name: "White", hex: "#f5f5f5" }],
  },
  // ——— Apple TV ———
  {
    slug: "appletv-4k-3rd-gen",
    name: "Apple TV 4K (3rd generation)",
    categorySlug: "appletv",
    description: "A15 Bionic. 4K HDR. Dolby Vision. Siri Remote. Thread. Wi‑Fi 6E. 64GB or 128GB.",
    shortDescription: "A15. 4K HDR. Siri Remote.",
    price: 129,
    currency: "USD",
    badge: "New",
    inStock: true,
    rating: 4.7,
    reviewCount: 1823,
    images: [U("1593359677879-a4bb92f829d1")],
    specs: [
      { label: "Chip", value: "A15 Bionic" },
      { label: "Video", value: "4K HDR; Dolby Vision; Dolby Atmos" },
      { label: "Storage", value: "64GB or 128GB" },
      { label: "Connectivity", value: "Wi‑Fi 6E; Ethernet; HDMI 2.1; Thread" },
    ],
    colors: [{ name: "Black", hex: "#1a1a1a" }],
  },
  {
    slug: "siri-remote",
    name: "Siri Remote (Apple TV)",
    categorySlug: "appletv",
    description: "Touch surface. Voice with Siri. Power button. USB-C charging. Works with Apple TV 4K.",
    shortDescription: "Touch. Siri. USB-C.",
    price: 59,
    currency: "USD",
    badge: "Premium",
    inStock: true,
    rating: 4.5,
    reviewCount: 3201,
    images: [U("1593359677879-a4bb92f829d1")],
    specs: [
      { label: "Features", value: "Touch surface; Siri; Power; Volume" },
      { label: "Charging", value: "USB-C" },
    ],
    colors: [{ name: "Silver", hex: "#e8e8e8" }],
  },
  // ——— إكسسوارات شاملة ———
  {
    slug: "magic-keyboard-mac",
    name: "Magic Keyboard (Mac)",
    categorySlug: "accessories",
    description: "Full-size. Scissor mechanism. Numeric keypad. Rechargeable. USB-C to Lightning. Silver.",
    shortDescription: "Full-size. Numeric keypad. Rechargeable.",
    price: 99,
    currency: "USD",
    badge: "Premium",
    inStock: true,
    rating: 4.6,
    reviewCount: 2341,
    images: [U("1583394838336-acd977736f90")],
    specs: [
      { label: "Layout", value: "Full-size with numeric keypad" },
      { label: "Battery", value: "Rechargeable; USB-C to Lightning" },
    ],
    colors: [{ name: "Silver", hex: "#e8e8e8" }],
  },
  {
    slug: "magic-mouse",
    name: "Magic Mouse",
    categorySlug: "accessories",
    description: "Multi-touch surface. Rechargeable. USB-C to Lightning. Gestures. Silver.",
    shortDescription: "Multi-touch. Rechargeable.",
    price: 79,
    currency: "USD",
    badge: "Premium",
    inStock: true,
    rating: 4.5,
    reviewCount: 3201,
    images: [U("1583394838336-acd977736f90")],
    specs: [
      { label: "Surface", value: "Multi-touch" },
      { label: "Battery", value: "Rechargeable; USB-C to Lightning" },
    ],
    colors: [{ name: "Silver", hex: "#e8e8e8" }],
  },
  {
    slug: "magic-trackpad",
    name: "Magic Trackpad",
    categorySlug: "accessories",
    description: "Large Force Touch trackpad. Rechargeable. USB-C to Lightning. Gestures.",
    shortDescription: "Force Touch. Rechargeable.",
    price: 129,
    currency: "USD",
    badge: "Premium",
    inStock: true,
    rating: 4.7,
    reviewCount: 1823,
    images: [U("1583394838336-acd977736f90")],
    specs: [
      { label: "Surface", value: "Force Touch; large format" },
      { label: "Battery", value: "Rechargeable; USB-C to Lightning" },
    ],
    colors: [{ name: "Silver", hex: "#e8e8e8" }],
  },
  {
    slug: "magsafe-charger",
    name: "MagSafe Charger",
    categorySlug: "accessories",
    description: "15W fast wireless charging for iPhone 12 and later. Magnetic alignment. USB-C cable (1m).",
    shortDescription: "15W. Magnetic. iPhone 12+.",
    price: 39,
    currency: "USD",
    badge: "Premium",
    inStock: true,
    rating: 4.6,
    reviewCount: 5203,
    images: [U("1609091839311-d5365f9ff1c5")],
    specs: [
      { label: "Output", value: "15W for MagSafe-compatible iPhone" },
      { label: "Cable", value: "1m USB-C to MagSafe" },
    ],
    colors: [{ name: "White", hex: "#f5f5f5" }],
  },
  {
    slug: "magsafe-duo",
    name: "MagSafe Duo Charger",
    categorySlug: "accessories",
    description: "Charge iPhone and Apple Watch together. Folds for travel. MagSafe + Watch charger.",
    shortDescription: "iPhone + Watch. Folds.",
    price: 129,
    currency: "USD",
    badge: "Premium",
    inStock: true,
    rating: 4.5,
    reviewCount: 892,
    images: [U("1609091839311-d5365f9ff1c5")],
    specs: [
      { label: "iPhone", value: "MagSafe 14W" },
      { label: "Watch", value: "Apple Watch charger" },
      { label: "Design", value: "Folds for travel" },
    ],
    colors: [{ name: "White", hex: "#f5f5f5" }],
  },
  {
    slug: "apple-pencil-pro",
    name: "Apple Pencil Pro",
    categorySlug: "accessories",
    description: "Squeeze. Barrel roll. Hover. Find My. USB-C. Compatible with iPad Pro M4, iPad Air M2.",
    shortDescription: "Squeeze. Barrel roll. Hover. Find My.",
    price: 129,
    currency: "USD",
    badge: "New",
    inStock: true,
    rating: 4.8,
    reviewCount: 654,
    images: [U("1624823183494-4d711f2f1a6c")],
    specs: [
      { label: "Features", value: "Squeeze; Barrel roll; Hover; Find My" },
      { label: "Charging", value: "USB-C" },
      { label: "Compatibility", value: "iPad Pro M4, iPad Air M2" },
    ],
    colors: [{ name: "White", hex: "#f5f5f5" }],
  },
  {
    slug: "apple-pencil-usb-c",
    name: "Apple Pencil (USB-C)",
    categorySlug: "accessories",
    description: "Precision. Tilt. USB-C. Affordable. Compatible with iPad 10th gen, iPad Air, iPad Pro.",
    shortDescription: "Precision. Tilt. USB-C.",
    price: 79,
    currency: "USD",
    badge: "Value",
    inStock: true,
    rating: 4.6,
    reviewCount: 2103,
    images: [U("1624823183494-4d711f2f1a6c")],
    specs: [
      { label: "Charging", value: "USB-C" },
      { label: "Compatibility", value: "iPad 10th gen, iPad Air, iPad Pro" },
    ],
    colors: [{ name: "White", hex: "#f5f5f5" }],
  },
  {
    slug: "smart-folio-ipad-pro",
    name: "Smart Folio for iPad Pro 13\"",
    categorySlug: "accessories",
    description: "Protects front and back. Folds for stand. Multiple viewing angles. Magnetic.",
    shortDescription: "Protects. Stand. Magnetic.",
    price: 79,
    currency: "USD",
    badge: "Premium",
    inStock: true,
    rating: 4.5,
    reviewCount: 892,
    images: [U("1583394838336-acd977736f90")],
    specs: [
      { label: "Compatibility", value: "iPad Pro 13\" (M4)" },
      { label: "Material", value: "Polyurethane" },
    ],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "White", hex: "#f5f5f5" },
    ],
  },
  {
    slug: "airtag-1pack",
    name: "AirTag (1 pack)",
    categorySlug: "accessories",
    description: "Track keys, bag, backpack. Precision Finding. Replaceable battery. Find My network.",
    shortDescription: "Track keys, bag. Find My.",
    price: 29,
    currency: "USD",
    badge: "Best Seller",
    inStock: true,
    rating: 4.6,
    reviewCount: 12034,
    images: [U("1583394838336-acd977736f90")],
    specs: [
      { label: "Precision Finding", value: "U1 chip; AR" },
      { label: "Battery", value: "Replaceable CR2032; up to 1 year" },
      { label: "Find My", value: "Secure; private" },
    ],
    colors: [{ name: "White", hex: "#f5f5f5" }],
  },
  {
    slug: "airtag-4pack",
    name: "AirTag (4 pack)",
    categorySlug: "accessories",
    description: "Four AirTags. Track keys, bags, luggage. Find My network. Replaceable battery.",
    shortDescription: "4-pack. Track everything.",
    price: 99,
    currency: "USD",
    badge: "Best Seller",
    inStock: true,
    rating: 4.7,
    reviewCount: 8234,
    images: [U("1583394838336-acd977736f90")],
    specs: [
      { label: "Quantity", value: "4 AirTags" },
      { label: "Precision Finding", value: "U1; Find My" },
    ],
    colors: [{ name: "White", hex: "#f5f5f5" }],
  },
  {
    slug: "homepod-mini",
    name: "HomePod mini",
    categorySlug: "accessories",
    description: "Room-filling sound. Siri. Intercom. Smart home hub. Thread. 360° audio. Five colors.",
    shortDescription: "Room-filling. Siri. Smart home.",
    price: 99,
    currency: "USD",
    badge: "Best Seller",
    inStock: true,
    rating: 4.6,
    reviewCount: 15234,
    images: [U("1593359677879-a4bb92f829d1")],
    specs: [
      { label: "Audio", value: "360° sound; Siri" },
      { label: "Smart home", value: "Hub; Thread" },
      { label: "Intercom", value: "HomePod to HomePod" },
    ],
    colors: [
      { name: "White", hex: "#f5f5f5" },
      { name: "Orange", hex: "#ff9f0a" },
      { name: "Blue", hex: "#4a90d9" },
      { name: "Yellow", hex: "#ffd60a" },
      { name: "Black", hex: "#1a1a1a" },
    ],
  },
  {
    slug: "35w-dual-usb-c",
    name: "35W Dual USB-C Port Power Adapter",
    categorySlug: "accessories",
    description: "Charge two devices. Compact. Foldable. USB-C. Ideal for iPhone and Apple Watch.",
    shortDescription: "35W. Dual port. Compact.",
    price: 59,
    currency: "USD",
    badge: "Premium",
    inStock: true,
    rating: 4.6,
    reviewCount: 3201,
    images: [U("1609091839311-d5365f9ff1c5")],
    specs: [
      { label: "Output", value: "35W total; 2× USB-C" },
      { label: "Design", value: "Compact; foldable" },
    ],
    colors: [{ name: "White", hex: "#f5f5f5" }],
  },
  {
    slug: "20w-usb-c-adapter",
    name: "20W USB-C Power Adapter",
    categorySlug: "accessories",
    description: "Fast charge for iPhone 8 and later. Compact. USB-C. Works with MagSafe.",
    shortDescription: "20W. iPhone fast charge.",
    price: 19,
    currency: "USD",
    badge: "Value",
    inStock: true,
    rating: 4.5,
    reviewCount: 18234,
    images: [U("1609091839311-d5365f9ff1c5")],
    specs: [
      { label: "Output", value: "20W USB-C" },
      { label: "Compatibility", value: "iPhone 8+; iPad" },
    ],
    colors: [{ name: "White", hex: "#f5f5f5" }],
  },
  {
    slug: "iphone-leather-case",
    name: "iPhone 16 Pro Leather Case",
    categorySlug: "accessories",
    description: "Premium leather. MagSafe. Protects camera. Multiple colors. Compatible with iPhone 16 Pro.",
    shortDescription: "Leather. MagSafe. Premium.",
    price: 59,
    currency: "USD",
    badge: "Premium",
    inStock: true,
    rating: 4.5,
    reviewCount: 2891,
    images: [U("1583394838336-acd977736f90")],
    specs: [
      { label: "Material", value: "Leather" },
      { label: "MagSafe", value: "Compatible" },
      { label: "Compatibility", value: "iPhone 16 Pro" },
    ],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "Midnight", hex: "#1e1e2e" },
      { name: "Brown", hex: "#8b6914" },
    ],
  },
  {
    slug: "iphone-silicone-case",
    name: "iPhone 16 Silicone Case",
    categorySlug: "accessories",
    description: "Soft-touch silicone. MagSafe. Protects camera. Many colors.",
    shortDescription: "Silicone. MagSafe. Colors.",
    price: 49,
    currency: "USD",
    badge: "Best Seller",
    inStock: true,
    rating: 4.6,
    reviewCount: 5203,
    images: [U("1583394838336-acd977736f90")],
    specs: [
      { label: "Material", value: "Silicone" },
      { label: "MagSafe", value: "Compatible" },
      { label: "Compatibility", value: "iPhone 16 / 16 Plus" },
    ],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "Blue", hex: "#4a90d9" },
      { name: "Pink", hex: "#ff9ff3" },
      { name: "Yellow", hex: "#ffd60a" },
      { name: "White", hex: "#f5f5f5" },
    ],
  },
  {
    slug: "sport-band-45mm",
    name: "Sport Band 45mm",
    categorySlug: "accessories",
    description: "Fluoroelastomer. Lightweight. Durable. For Apple Watch 45mm/49mm. Many colors.",
    shortDescription: "Fluoroelastomer. 45/49mm.",
    price: 49,
    currency: "USD",
    badge: "Premium",
    inStock: true,
    rating: 4.6,
    reviewCount: 8234,
    images: [U("1434493789847-2f02dc6ca35d")],
    specs: [
      { label: "Size", value: "45mm / 49mm" },
      { label: "Material", value: "Fluoroelastomer" },
    ],
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "White", hex: "#f5f5f5" },
      { name: "Midnight", hex: "#1e1e2e" },
      { name: "Red", hex: "#ff3b30" },
      { name: "Blue", hex: "#4a90d9" },
      { name: "Green", hex: "#34c759" },
    ],
  },
  {
    slug: "magic-keyboard-ipad-air",
    name: "Magic Keyboard for iPad Air 11\"",
    categorySlug: "accessories",
    description: "Floating design. Trackpad. Backlit. USB-C. For iPad Air 11\" (M2).",
    shortDescription: "Floating. Trackpad. iPad Air 11\".",
    price: 299,
    currency: "USD",
    badge: "Premium",
    inStock: true,
    rating: 4.7,
    reviewCount: 654,
    images: [U("1583394838336-acd977736f90")],
    specs: [
      { label: "Compatibility", value: "iPad Air 11\" (M2)" },
      { label: "Features", value: "Trackpad; backlit; USB-C" },
    ],
    colors: [{ name: "White", hex: "#f5f5f5" }],
  },
  {
    slug: "usb-c-to-usb-c-1m",
    name: "USB-C to USB-C Cable (1m)",
    categorySlug: "accessories",
    description: "Charge and sync. 1 meter. USB 2. Mac, iPad, iPhone 15.",
    shortDescription: "1m. USB-C. Charge & sync.",
    price: 19,
    currency: "USD",
    badge: "Value",
    inStock: true,
    rating: 4.5,
    reviewCount: 9234,
    images: [U("1609091839311-d5365f9ff1c5")],
    specs: [
      { label: "Length", value: "1 m" },
      { label: "Connector", value: "USB-C to USB-C" },
    ],
    colors: [{ name: "White", hex: "#f5f5f5" }],
  },
  {
    slug: "96w-usb-c-adapter",
    name: "96W USB-C Power Adapter",
    categorySlug: "accessories",
    description: "Fast charge for 14\" and 16\" MacBook Pro. USB-C. Compact.",
    shortDescription: "96W. MacBook Pro fast charge.",
    price: 99,
    currency: "USD",
    badge: "Premium",
    inStock: true,
    rating: 4.6,
    reviewCount: 1823,
    images: [U("1609091839311-d5365f9ff1c5")],
    specs: [
      { label: "Output", value: "96W USB-C" },
      { label: "Compatibility", value: "14\" and 16\" MacBook Pro" },
    ],
    colors: [{ name: "White", hex: "#f5f5f5" }],
  },
];
